[package]
name = "OpenT5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.0"
lazy_static = "1.4.0"
bitflags = "1.3.2"
num = "0.4.0"
arrayvec = "0.7.2"
wgpu = "0.13.1"
openh264 = "0.2.15"
winit = "0.27.3"
env_logger = "0.9"
log = "0.4"
num-derive = "0.3"
num-traits = "0.2"
pollster = "0.2"
nix = "0.25.0"
sysinfo = "0.26.4"
cfg-if="1.0.0"
raw-window-handle="0.5.0"

windows =  { version = "0.42.0", features = ["Win32_Foundation", 
            "Win32_System_Threading","Win32_System_LibraryLoader", 
            "Win32_System_Environment", "Win32_UI_WindowsAndMessaging", 
            "Win32_System_Diagnostics_Debug", "Win32_System_Kernel", 
            "Win32_System_Memory", "Win32_UI_Shell"] }
sscanf = "0.3.1"
