unstable_features = true
max_width = 80
doc_comment_code_block_width = 80
tab_spaces = 4
hard_tabs = false
format_macro_bodies = true
format_macro_matchers = true
format_code_in_doc_comments = true
format_strings = true
normalize_comments = true
imports_granularity = "Crate"
wrap_comments = true
comment_width = 80
