name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-win_d3d9:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Nightly
      run: rustup toolchain add nightly
    - name: Build
      run: cargo +nightly build --verbose --features windows_use_d3d9
    
  build-win_wgpu:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Nightly
      run: rustup toolchain add nightly
    - name: Build
      run: cargo +nightly build --verbose --features windows_use_wgpu
      
  build-linux_wayland:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Nightly
      run: rustup toolchain add nightly
    - name: Install Dependencies
      run: sudo apt install libgtk-4-dev libudev-dev
    - name: Build
      run: cargo +nightly build --verbose --features linux_use_wayland,linux_use_wgpu
      
  build-linux_xlib:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Nightly
      run: rustup toolchain add nightly
    - name: Install Dependencies
      run: sudo apt install libgtk-4-dev libudev-dev
    - name: Build
      run: cargo +nightly build --verbose --features linux_use_xlib,linux_use_wgpu
      
  build-macos_appkit:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Nightly
      run: rustup toolchain add nightly
    - name: Install Dependencies
      run: brew install xquartz libxrandr
    - name: Build
      run: cargo +nightly build --verbose --features macos_use_appkit,macos_use_wgpu
      
  build-macos_xlib:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Nightly
      run: rustup toolchain add nightly
    - name: Install Dependencies
      run: brew install xquartz libxrandr
    - name: Build
      run: cargo +nightly build --verbose --features macos_use_xlib,macos_use_wgpu
