name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Nightly
      run: rustup toolchain add nightly
    - name: Build
      run: cargo +nightly build --verbose
  
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Nightly
      run: rustup toolchain add nightly
    - name: Install Dependencies
      run: sudo apt install libgtk-4-dev libudev-dev
    - name: Build
      run: cargo +nightly build --verbose
      
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Nightly
      run: rustup toolchain add nightly
    - name: Install Dependencies
      run: brew install --cask xquartz libxrandr
    - name: Build
      run: cargo +nightly build --verbose
